language: python
python:
 - "3.2"
 - "2.7"
 - "pypy"
branches:
 only:
  - master
install: python setup.py install
before_script: mysql -e 'create database mysqldb_test charset utf8;'
script: TESTDB=travis.cnf nosetests
